default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: tech-podium_development

test:
  <<: *default
  database: tech-podium_test

production:
  <<: *default
  database: tech-podium_production
